export type SymbolEntry = { d: string; l: string };
export type SymbolCat = {
  id: string;
  label: string;
  title: string;
  symbols: SymbolEntry[];
};

export const SYMBOL_CATS: SymbolCat[] = [
  {
    id: "greek",
    label: "α",
    title: "Greek",
    symbols: [
      { d: "α", l: "\\alpha" },
      { d: "β", l: "\\beta" },
      { d: "γ", l: "\\gamma" },
      { d: "δ", l: "\\delta" },
      { d: "ε", l: "\\epsilon" },
      { d: "ζ", l: "\\zeta" },
      { d: "η", l: "\\eta" },
      { d: "θ", l: "\\theta" },
      { d: "ι", l: "\\iota" },
      { d: "κ", l: "\\kappa" },
      { d: "λ", l: "\\lambda" },
      { d: "μ", l: "\\mu" },
      { d: "ν", l: "\\nu" },
      { d: "ξ", l: "\\xi" },
      { d: "π", l: "\\pi" },
      { d: "ρ", l: "\\rho" },
      { d: "σ", l: "\\sigma" },
      { d: "τ", l: "\\tau" },
      { d: "υ", l: "\\upsilon" },
      { d: "φ", l: "\\phi" },
      { d: "χ", l: "\\chi" },
      { d: "ψ", l: "\\psi" },
      { d: "ω", l: "\\omega" },
      { d: "Γ", l: "\\Gamma" },
      { d: "Δ", l: "\\Delta" },
      { d: "Θ", l: "\\Theta" },
      { d: "Λ", l: "\\Lambda" },
      { d: "Ξ", l: "\\Xi" },
      { d: "Π", l: "\\Pi" },
      { d: "Σ", l: "\\Sigma" },
      { d: "Υ", l: "\\Upsilon" },
      { d: "Φ", l: "\\Phi" },
      { d: "Ψ", l: "\\Psi" },
      { d: "Ω", l: "\\Omega" },
    ],
  },
  {
    id: "bigops",
    label: "∑",
    title: "Big Operators",
    symbols: [
      { d: "∑", l: "\\sum" },
      { d: "∏", l: "\\prod" },
      { d: "∐", l: "\\coprod" },
      { d: "∫", l: "\\int" },
      { d: "∬", l: "\\iint" },
      { d: "∭", l: "\\iiint" },
      { d: "∮", l: "\\oint" },
      { d: "⋃", l: "\\bigcup" },
      { d: "⋂", l: "\\bigcap" },
      { d: "⊕", l: "\\bigoplus" },
      { d: "⊗", l: "\\bigotimes" },
      { d: "⋁", l: "\\bigvee" },
      { d: "⋀", l: "\\bigwedge" },
      { d: "⨆", l: "\\bigsqcup" },
      { d: "⊎", l: "\\biguplus" },
    ],
  },
  {
    id: "relations",
    label: "≤",
    title: "Relations",
    symbols: [
      { d: "≠", l: "\\neq" },
      { d: "≤", l: "\\leq" },
      { d: "≥", l: "\\geq" },
      { d: "≪", l: "\\ll" },
      { d: "≫", l: "\\gg" },
      { d: "≈", l: "\\approx" },
      { d: "∼", l: "\\sim" },
      { d: "≃", l: "\\simeq" },
      { d: "≅", l: "\\cong" },
      { d: "≡", l: "\\equiv" },
      { d: "∝", l: "\\propto" },
      { d: "∈", l: "\\in" },
      { d: "∉", l: "\\notin" },
      { d: "∋", l: "\\ni" },
      { d: "⊂", l: "\\subset" },
      { d: "⊃", l: "\\supset" },
      { d: "⊆", l: "\\subseteq" },
      { d: "⊇", l: "\\supseteq" },
      { d: "⊊", l: "\\subsetneq" },
      { d: "⊋", l: "\\supsetneq" },
      { d: "∥", l: "\\parallel" },
      { d: "⊥", l: "\\perp" },
      { d: "∣", l: "\\mid" },
      { d: "∤", l: "\\nmid" },
      { d: "≺", l: "\\prec" },
      { d: "≻", l: "\\succ" },
      { d: "⪯", l: "\\preceq" },
      { d: "⪰", l: "\\succeq" },
    ],
  },
  {
    id: "arrows",
    label: "→",
    title: "Arrows",
    symbols: [
      { d: "→", l: "\\rightarrow" },
      { d: "←", l: "\\leftarrow" },
      { d: "↔", l: "\\leftrightarrow" },
      { d: "⇒", l: "\\Rightarrow" },
      { d: "⇐", l: "\\Leftarrow" },
      { d: "⇔", l: "\\Leftrightarrow" },
      { d: "⟶", l: "\\longrightarrow" },
      { d: "⟵", l: "\\longleftarrow" },
      { d: "⟹", l: "\\Longrightarrow" },
      { d: "⟸", l: "\\Longleftarrow" },
      { d: "⟺", l: "\\Longleftrightarrow" },
      { d: "↑", l: "\\uparrow" },
      { d: "↓", l: "\\downarrow" },
      { d: "↕", l: "\\updownarrow" },
      { d: "↗", l: "\\nearrow" },
      { d: "↘", l: "\\searrow" },
      { d: "↖", l: "\\nwarrow" },
      { d: "↙", l: "\\swarrow" },
      { d: "↦", l: "\\mapsto" },
      { d: "↪", l: "\\hookrightarrow" },
      { d: "↩", l: "\\hookleftarrow" },
    ],
  },
  {
    id: "binops",
    label: "⊕",
    title: "Binary Operators",
    symbols: [
      { d: "±", l: "\\pm" },
      { d: "∓", l: "\\mp" },
      { d: "×", l: "\\times" },
      { d: "÷", l: "\\div" },
      { d: "⋅", l: "\\cdot" },
      { d: "∗", l: "\\ast" },
      { d: "⋆", l: "\\star" },
      { d: "∘", l: "\\circ" },
      { d: "•", l: "\\bullet" },
      { d: "⊕", l: "\\oplus" },
      { d: "⊖", l: "\\ominus" },
      { d: "⊗", l: "\\otimes" },
      { d: "⊘", l: "\\oslash" },
      { d: "⊙", l: "\\odot" },
      { d: "∪", l: "\\cup" },
      { d: "∩", l: "\\cap" },
      { d: "⊔", l: "\\sqcup" },
      { d: "⊓", l: "\\sqcap" },
      { d: "∧", l: "\\wedge" },
      { d: "∨", l: "\\vee" },
      { d: "∖", l: "\\setminus" },
      { d: "◇", l: "\\diamond" },
      { d: "◁", l: "\\triangleleft" },
      { d: "▷", l: "\\triangleright" },
    ],
  },
  {
    id: "logic",
    label: "∀",
    title: "Logic & Sets",
    symbols: [
      { d: "∀", l: "\\forall" },
      { d: "∃", l: "\\exists" },
      { d: "∄", l: "\\nexists" },
      { d: "¬", l: "\\neg" },
      { d: "∅", l: "\\varnothing" },
      { d: "ℝ", l: "\\mathbb{R}" },
      { d: "ℤ", l: "\\mathbb{Z}" },
      { d: "ℕ", l: "\\mathbb{N}" },
      { d: "ℚ", l: "\\mathbb{Q}" },
      { d: "ℂ", l: "\\mathbb{C}" },
      { d: "ℙ", l: "\\mathbb{P}" },
    ],
  },
  {
    id: "misc",
    label: "∞",
    title: "Miscellaneous",
    symbols: [
      { d: "∞", l: "\\infty" },
      { d: "∂", l: "\\partial" },
      { d: "∇", l: "\\nabla" },
      { d: "ℏ", l: "\\hbar" },
      { d: "ℓ", l: "\\ell" },
      { d: "℘", l: "\\wp" },
      { d: "ℜ", l: "\\Re" },
      { d: "ℑ", l: "\\Im" },
      { d: "ℵ", l: "\\aleph" },
      { d: "∠", l: "\\angle" },
      { d: "′", l: "\\prime" },
      { d: "…", l: "\\ldots" },
      { d: "⋯", l: "\\cdots" },
      { d: "⋮", l: "\\vdots" },
      { d: "⋱", l: "\\ddots" },
      { d: "√", l: "\\surd" },
      { d: "♯", l: "\\sharp" },
      { d: "♭", l: "\\flat" },
      { d: "♮", l: "\\natural" },
    ],
  },
];
